[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 4


[rpc_endpoints]
mantle = "${MANTLE_RPC}"

[etherscan]
mantle = { key = "${ETHERSCAN}" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config